# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_view(object):
    def setupUi(self, Admin_view):
        Admin_view.setObjectName("Admin_view")
        Admin_view.resize(985, 594)
        Admin_view.setMinimumSize(QtCore.QSize(985, 594))
        Admin_view.setMaximumSize(QtCore.QSize(985, 594))
        Admin_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.current_profile_pic = QtWidgets.QLabel(Admin_view)
        self.current_profile_pic.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.current_profile_pic.setText("")
        self.current_profile_pic.setPixmap(QtGui.QPixmap("../noprofile1.png"))
        self.current_profile_pic.setObjectName("current_profile_pic")
        self.label_selected_name = QtWidgets.QLabel(Admin_view)
        self.label_selected_name.setGeometry(QtCore.QRect(70, 10, 211, 16))
        self.label_selected_name.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";")
        self.label_selected_name.setObjectName("label_selected_name")
        self.pushButton_log_out = QtWidgets.QPushButton(Admin_view)
        self.pushButton_log_out.setGeometry(QtCore.QRect(900, 20, 75, 23))
        self.pushButton_log_out.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"border-radius: 15px;")
        self.pushButton_log_out.setObjectName("pushButton_log_out")
        self.label_status = QtWidgets.QLabel(Admin_view)
        self.label_status.setGeometry(QtCore.QRect(550, 10, 151, 16))
        self.label_status.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";")
        self.label_status.setObjectName("label_status")
        self.pushButton_edit_user = QtWidgets.QPushButton(Admin_view)
        self.pushButton_edit_user.setGeometry(QtCore.QRect(0, 60, 61, 23))
        self.pushButton_edit_user.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"border-radius: 15px;")
        self.pushButton_edit_user.setObjectName("pushButton_edit_user")
        self.label_selected_tel = QtWidgets.QLabel(Admin_view)
        self.label_selected_tel.setGeometry(QtCore.QRect(70, 30, 211, 16))
        self.label_selected_tel.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";")
        self.label_selected_tel.setObjectName("label_selected_tel")
        self.label_selected_province = QtWidgets.QLabel(Admin_view)
        self.label_selected_province.setGeometry(QtCore.QRect(320, 10, 211, 16))
        self.label_selected_province.setStyleSheet("font: 25 8pt \"Microsoft JhengHei UI Light\";")
        self.label_selected_province.setObjectName("label_selected_province")
        self.scrollArea_all_user = QtWidgets.QScrollArea(Admin_view)
        self.scrollArea_all_user.setGeometry(QtCore.QRect(9, 109, 971, 481))
        self.scrollArea_all_user.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.scrollArea_all_user.setWidgetResizable(True)
        self.scrollArea_all_user.setObjectName("scrollArea_all_user")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_all_user.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Admin_view)
        QtCore.QMetaObject.connectSlotsByName(Admin_view)

    def retranslateUi(self, Admin_view):
        _translate = QtCore.QCoreApplication.translate
        Admin_view.setWindowTitle(_translate("Admin_view", "Form"))
        self.label_selected_name.setText(_translate("Admin_view", "Name"))
        self.pushButton_log_out.setText(_translate("Admin_view", "Log out"))
        self.label_status.setText(_translate("Admin_view", "Status"))
        self.pushButton_edit_user.setText(_translate("Admin_view", "Edit"))
        self.label_selected_tel.setText(_translate("Admin_view", "Tel"))
        self.label_selected_province.setText(_translate("Admin_view", "Province"))
