# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profile_view(object):
    def setupUi(self, profile_view):
        profile_view.setObjectName("profile_view")
        profile_view.resize(1000, 1000)
        profile_view.setMinimumSize(QtCore.QSize(1000, 1000))
        profile_view.setMaximumSize(QtCore.QSize(1000, 1000))
        profile_view.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label = QtWidgets.QLabel(profile_view)
        self.label.setGeometry(QtCore.QRect(440, 30, 121, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../noprofile3.png"))
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(profile_view)
        self.label_name.setGeometry(QtCore.QRect(430, 170, 161, 16))
        self.label_name.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_name.setObjectName("label_name")
        self.label_email = QtWidgets.QLabel(profile_view)
        self.label_email.setGeometry(QtCore.QRect(430, 220, 161, 16))
        self.label_email.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_email.setObjectName("label_email")
        self.pushButton_edit_profile = QtWidgets.QPushButton(profile_view)
        self.pushButton_edit_profile.setGeometry(QtCore.QRect(400, 810, 181, 41))
        self.pushButton_edit_profile.setStyleSheet("border-radius: 15px;\n"
"font: 25 8pt \"Microsoft JhengHei UI Light\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.pushButton_edit_profile.setObjectName("pushButton_edit_profile")
        self.label_status_prompt = QtWidgets.QLabel(profile_view)
        self.label_status_prompt.setGeometry(QtCore.QRect(430, 370, 61, 16))
        self.label_status_prompt.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_status_prompt.setObjectName("label_status_prompt")
        self.label_status = QtWidgets.QLabel(profile_view)
        self.label_status.setGeometry(QtCore.QRect(500, 370, 161, 16))
        self.label_status.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_status.setObjectName("label_status")
        self.label_tel = QtWidgets.QLabel(profile_view)
        self.label_tel.setGeometry(QtCore.QRect(430, 270, 161, 16))
        self.label_tel.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_tel.setObjectName("label_tel")
        self.radioButton = QtWidgets.QRadioButton(profile_view)
        self.radioButton.setGeometry(QtCore.QRect(430, 430, 221, 20))
        self.radioButton.setStyleSheet("\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(profile_view)
        self.radioButton_2.setGeometry(QtCore.QRect(430, 480, 221, 20))
        self.radioButton_2.setStyleSheet("\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(profile_view)
        self.radioButton_3.setGeometry(QtCore.QRect(430, 530, 221, 20))
        self.radioButton_3.setStyleSheet("\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.doctor = QtWidgets.QLabel(profile_view)
        self.doctor.setGeometry(QtCore.QRect(440, 580, 191, 211))
        self.doctor.setText("")
        self.doctor.setPixmap(QtGui.QPixmap("../doc1.png"))
        self.doctor.setObjectName("doctor")
        self.label_province = QtWidgets.QLabel(profile_view)
        self.label_province.setGeometry(QtCore.QRect(430, 320, 161, 16))
        self.label_province.setStyleSheet("font: 25 14pt \"Microsoft JhengHei UI Light\";")
        self.label_province.setObjectName("label_province")
        self.lineEdit_name = QtWidgets.QLineEdit(profile_view)
        self.lineEdit_name.setGeometry(QtCore.QRect(530, 170, 161, 21))
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_email = QtWidgets.QLineEdit(profile_view)
        self.lineEdit_email.setGeometry(QtCore.QRect(530, 220, 161, 21))
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_tel = QtWidgets.QLineEdit(profile_view)
        self.lineEdit_tel.setGeometry(QtCore.QRect(530, 270, 161, 21))
        self.lineEdit_tel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.lineEdit_province = QtWidgets.QLineEdit(profile_view)
        self.lineEdit_province.setGeometry(QtCore.QRect(530, 320, 161, 21))
        self.lineEdit_province.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 290 14pt \"Microsoft JhengHei UI Light\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_province.setObjectName("lineEdit_province")

        self.retranslateUi(profile_view)
        QtCore.QMetaObject.connectSlotsByName(profile_view)

    def retranslateUi(self, profile_view):
        _translate = QtCore.QCoreApplication.translate
        profile_view.setWindowTitle(_translate("profile_view", "Form"))
        self.label_name.setText(_translate("profile_view", "Name"))
        self.label_email.setText(_translate("profile_view", "Email"))
        self.pushButton_edit_profile.setText(_translate("profile_view", "Edit Profile"))
        self.label_status_prompt.setText(_translate("profile_view", "Status:"))
        self.label_status.setText(_translate("profile_view", "Infected?"))
        self.label_tel.setText(_translate("profile_view", "Tel"))
        self.radioButton.setText(_translate("profile_view", "Vaccinated"))
        self.radioButton_2.setText(_translate("profile_view", "Infected"))
        self.radioButton_3.setText(_translate("profile_view", "Death"))
        self.label_province.setText(_translate("profile_view", "Province"))
